import { useEffect, useState } from 'react';
import ExcelJS from 'exceljs';
import { listReceiptLoans, listReceipts } from './api';
import { printLoanDetail } from './printUtils';

function money(v){return `₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`}
async function request(path,opts={}){const token=localStorage.getItem('chfpl_admin_token');const r=await fetch(`/api/admin/${path}`,{method:opts.method||'GET',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:opts.body?JSON.stringify(opts.body):undefined});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||'Request failed');return d}

export default function LoanCases(){
 const [loans,setLoans]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false);
 const [preview,setPreview]=useState(null),[previewLoading,setPreviewLoading]=useState(false);
 const [importing,setImporting]=useState(false),[importResult,setImportResult]=useState(null);

 const IMPORT_HEADERS=[
  ['application_no','Application No.'],['loan_account_no','Loan Account No.*'],['application_status','Application Status'],['case_status','Case Status'],
  ['customer_name','Customer Name*'],['customer_phone','Customer Mobile*'],['customer_email','Customer Email'],['customer_dob','Customer DOB'],['customer_gender','Customer Gender'],['customer_address','Customer Address'],['customer_landmark','Customer Landmark'],['customer_city','Customer City'],['customer_state','Customer State'],['customer_pincode','Customer Pincode'],['customer_ownership_status','Applicant Own / Rented'],['customer_pan','Customer PAN'],['customer_aadhaar_masked','Customer Aadhaar (masked)'],['customer_electricity_ca_no','Customer Electricity C.A No.'],['customer_occupation','Customer Occupation'],['customer_monthly_income','Customer Monthly Income'],
  ['dealer_code','Dealer Code'],['dealer_name','Dealer Name'],['vehicle_model_id','Vehicle Model ID'],['vehicle_model_name','Vehicle Model Name'],['vehicle_price','Vehicle Price'],['down_payment','Down Payment'],['loan_amount_requested','Loan Amount'],['tenure_months','Tenure (Months)'],
  ['physical_register_serial_no','Physical Register No.'],['vehicle_no','Vehicle No.'],['chassis_no','Chassis No.'],['ledger_no','Ledger / Register No.'],['file_no','File No.'],['file_record_no','File Record No.'],['cheques_qty','Cheques Qty'],['hypothecation','Hypothecation'],['do_no','D.O No. (Loan No.)'],['case_received_date','Case Received Date'],['fi_send_date','FI Assigned Date'],['fi_received_date','FI Approved / Received Date'],['fi_status','FI Status'],['fi_executive_name','Field Executive'],['sanction_date','Sanction Date'],['approved_by','Approved By'],['file_received_date','File Received Date'],['file_check_date','File Check Date'],['interest_rate','Interest Rate %'],['interest_amount','Total Interest'],['principal_amount','Loan Sanctioned Amount'],['emi_no','Loan Tenor / EMI No.'],['emi_amount','Loan EMI'],['vehicle_registration_date','Vehicle Registration Date'],['approved_at','Approved At'],['approval_valid_until','Approval Valid Until'],['cibil_score','CIBIL Score'],['cibil_checked_at','CIBIL Checked At'],['disbursement_date','Disbursed Date'],['disbursed_amount','Disbursed Amount'],['suit_filed_at','Suit Filed At'],['vehicle_seized_at','Vehicle Seized At'],
  ['guarantor_1_name','Guarantor 1 Name'],['guarantor_1_relation','Guarantor 1 Relation'],['guarantor_1_phone','Guarantor 1 Phone'],['guarantor_1_address','Guarantor 1 Address'],['guarantor_1_ownership_status','Guarantor 1 Own / Rented'],['guarantor_1_landmark','Guarantor 1 Landmark'],['guarantor_1_pan','Guarantor 1 PAN'],['guarantor_1_aadhaar_masked','Guarantor 1 Aadhaar (masked)'],['guarantor_1_electricity_ca_no','Guarantor 1 Electricity C.A No.'],
  ['guarantor_2_name','Guarantor 2 Name'],['guarantor_2_relation','Guarantor 2 Relation'],['guarantor_2_phone','Guarantor 2 Phone'],['guarantor_2_address','Guarantor 2 Address'],['guarantor_2_ownership_status','Guarantor 2 Own / Rented'],['guarantor_2_landmark','Guarantor 2 Landmark'],['guarantor_2_pan','Guarantor 2 PAN'],['guarantor_2_aadhaar_masked','Guarantor 2 Aadhaar (masked)'],['guarantor_2_electricity_ca_no','Guarantor 2 Electricity C.A No.'],
  ['co_borrower_name','Co-Borrower Name'],['co_borrower_relation','Co-Borrower Relation'],['co_borrower_phone','Co-Borrower Phone'],['co_borrower_email','Co-Borrower Email'],['co_borrower_dob','Co-Borrower DOB'],['co_borrower_gender','Co-Borrower Gender'],['co_borrower_address','Co-Borrower Address'],['co_borrower_landmark','Co-Borrower Landmark'],['co_borrower_city','Co-Borrower City'],['co_borrower_state','Co-Borrower State'],['co_borrower_pincode','Co-Borrower Pincode'],['co_borrower_ownership_status','Co-Borrower Own / Rented'],['co_borrower_pan','Co-Borrower PAN'],['co_borrower_aadhaar_masked','Co-Borrower Aadhaar (masked)'],['co_borrower_electricity_ca_no','Co-Borrower Electricity C.A No.'],['co_borrower_occupation','Co-Borrower Occupation'],['co_borrower_monthly_income','Co-Borrower Monthly Income']
 ];
 async function downloadTemplate(){
   const a=document.createElement('a'); a.href='/CHF_Loan_Case_Import_Template.xlsx'; a.download='CHF_Loan_Case_Import_Template.xlsx'; document.body.appendChild(a); a.click(); a.remove();
 }
 async function importFile(e){
   const file=e.target.files?.[0]; e.target.value=''; if(!file)return; setImportResult(null);setError('');setImporting(true);
   try{ const wb=new ExcelJS.Workbook(); await wb.xlsx.load(await file.arrayBuffer()); const ws=wb.worksheets[0]; if(!ws)throw new Error('Excel sheet not found.');
     const headers=(ws.getRow(1).values||[]).slice(1).map(v=>String(v||'').trim());
     const normalizeHeader=(h)=>String(h||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
     const headerAliases={
       's no':'legacy_sno','case status':'case_status','own rented':'customer_ownership_status','own rented applicant':'customer_ownership_status','own rented applicant name':'customer_ownership_status',
       'hypothication':'hypothecation','hypothecation':'hypothecation','d o no loan no':'do_no','do no loan no':'do_no','loan no':'loan_account_no',
       'applicant name':'customer_name','mobile number':'customer_phone','address':'customer_address','land mark':'customer_landmark','aadhaar card no':'customer_aadhaar_masked','pan no':'customer_pan','c a no electricity':'customer_electricity_ca_no',
       'co applicant name':'co_borrower_name','co applicant relation':'co_borrower_relation','relation':'co_borrower_relation','co applicant address':'co_borrower_address','co applicant mobile no':'co_borrower_phone','co applicant aadhaar card no':'co_borrower_aadhaar_masked','co applicant pan no':'co_borrower_pan','co applicant c a no electricity':'co_borrower_electricity_ca_no','co applicant own rented':'co_borrower_ownership_status',
       'guarantor name':'guarantor_1_name','guarantor address':'guarantor_1_address','guarantor mobile no':'guarantor_1_phone','guarantor aadhaar card no':'guarantor_1_aadhaar_masked','guarantor pan no':'guarantor_1_pan','guarantor c a no electricity':'guarantor_1_electricity_ca_no','guarantor own rented':'guarantor_1_ownership_status',
       'fi send date':'fi_send_date','fi received date':'fi_received_date','fi stauts':'fi_status','fi status':'fi_status','fi excutive name':'fi_executive_name','fi executive name':'fi_executive_name','date to dealer sanction':'sanction_date','approved by':'approved_by','file received date':'file_received_date','file check date':'file_check_date','disbursed date':'disbursement_date','loan amount':'loan_amount_requested','interest rate':'interest_rate','interest rate percent':'interest_rate','interest amt':'interest_amount','interest amount':'interest_amount','principal amount':'principal_amount','emi no':'emi_no','emi':'emi_amount','invoice date':'vehicle_registration_date','disbursed amt':'disbursed_amount','ledger no':'ledger_no','vehicle no':'vehicle_no'
     };
     const keyByHeader=Object.fromEntries(IMPORT_HEADERS.map(([k,label])=>[normalizeHeader(label),k]));
     Object.assign(keyByHeader,headerAliases);
     const rows=[]; ws.eachRow((row,n)=>{if(n===1)return; const vals=(row.values||[]).slice(1); const obj={}; headers.forEach((h,i)=>{const key=keyByHeader[normalizeHeader(h)];if(key)obj[key]=vals[i]??'';}); if(Object.values(obj).some(v=>String(v??'').trim()!==''))rows.push(obj);});
     if(!rows.length)throw new Error('No data rows found.'); if(rows.length>500)throw new Error('Maximum 500 rows per import.');
     const token=localStorage.getItem('chfpl_admin_token'); const resp=await fetch('/api/admin/import-loan-cases',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({rows})}); const d=await resp.json().catch(()=>({})); if(!resp.ok||!d.success)throw new Error(d.error||'Import failed'); setImportResult(d); await load();
   }catch(err){setError(err.message)}finally{setImporting(false)}
 }

 async function load(){setLoading(true);setError('');try{const d=await request('loan-cases');setLoans(d.loans||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function openPreview(row){
   setPreview({loan:row,receipts:[]});setPreviewLoading(true);setError('');
   try{
     const [ld,rd]=await Promise.all([listReceiptLoans(),listReceipts()]);
     const loan=(ld.loans||[]).find(x=>String(x.id)===String(row.id))||row;
     const receipts=(rd.receipts||[]).filter(r=>String(r.loan_application_id)===String(row.id));
     setPreview({loan,receipts});
   }catch(e){setPreview({loan:row,receipts:[]});setError(e.message)}finally{setPreviewLoading(false)}
 }
 async function save(e){e.preventDefault();setSaving(true);setError('');try{await request('loan-cases',{method:'POST',body:editing});setMessage('Loan case updated.');setEditing(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="admin-page">
   <div className="admin-page-head"><div><div className="admin-eyebrow">LOAN CASE MANAGEMENT</div><h1>Loan Cases</h1><p>Loan No. par click karke side panel me complete detail dekhein aur print karein.</p></div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><div className="admin-count">{loans.length} loans</div><button className="admin-btn secondary" onClick={downloadTemplate}>⬇ Excel Template</button><label className="admin-btn" style={{cursor:importing?'wait':'pointer',opacity:importing?.65:1}}>{importing?'Importing…':'⬆ Import Loan Cases'}<input type="file" accept=".xlsx,.xls,.csv" onChange={importFile} disabled={importing} style={{display:'none'}}/></label></div></div>
   {error&&<div className="admin-alert error">⚠ {error}</div>}{message&&<div className="admin-alert success">✓ {message}</div>}
   {importResult&&<div className="admin-alert success">✓ Import complete: {importResult.created} created, {importResult.updated} updated, {importResult.failed} failed. {importResult.failed>0&&<details style={{marginTop:8}}><summary>View failed rows</summary><div style={{marginTop:8,maxHeight:180,overflow:'auto'}}>{importResult.results.filter(r=>r.status==='error').map(r=><div key={r.row}>Row {r.row} — {r.loan_account_no||'—'}: {r.error}</div>)}</div></details>}</div>}
   <section className="admin-card staff-list-card"><div className="admin-card-title"><div><h2>Loan Register</h2><span>Loan account wise case information</span></div><button className="admin-btn secondary" onClick={load}>↻ Refresh</button></div>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Loan</th><th>Customer</th><th>Vehicle</th><th>Ledger</th><th>File</th><th>Case Status</th><th>Repo</th><th>Action</th></tr></thead><tbody>
      {loading?<tr><td colSpan="8" className="empty-cell">Loading…</td></tr>:loans.map(l=><tr key={l.id}>
        <td><button type="button" onClick={()=>openPreview(l)} style={{background:'none',border:0,padding:0,cursor:'pointer',textAlign:'left'}}><strong style={{color:'#8d1f24',textDecoration:'underline'}}>{l.loan_account_no}</strong><div className="muted">{l.application_no}</div></button></td>
        <td>{l.customer_profiles?.full_name||'—'}<div className="muted">{l.customer_profiles?.phone||''}</div></td>
        <td>{l.vehicle_model_master?.model_name||'—'}<div className="muted">{l.vehicle_no||l.chassis_no||''}</div></td>
        <td>{l.ledger_no||'—'}</td><td>{l.file_no||'—'}<div className="muted">{l.file_record_no||''}</div></td>
        <td><span className="role-pill admin">{String(l.case_status||'active').replaceAll('_',' ')}</span></td>
        <td>{l.vehicle_repossessions?.[0]?<span className="role-pill admin">Repo Done</span>:<span className="muted">—</span>}</td>
        <td><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button className="admin-btn small" onClick={()=>openPreview(l)}>View / Print</button><button className="admin-btn small secondary" onClick={()=>setEditing({...l,loan_application_id:l.id,case_status:l.case_status||'active',loan_status:l.application_status||'sanctioned',vehicle_no:l.vehicle_no||'',chassis_no:l.chassis_no||'',ledger_no:l.ledger_no||'',file_no:l.file_no||'',file_record_no:l.file_record_no||'',cheques_qty:l.cheques_qty||0,disbursement_date:l.disbursement_date||'',disbursed_amount:l.disbursed_amount||''})}>Edit</button></div></td>
      </tr>)}{!loading&&!loans.length&&<tr><td colSpan="8" className="empty-cell">No created loan accounts yet.</td></tr>}
    </tbody></table></div>
   </section>
   {editing&&<div className="admin-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><section className="admin-modal loan-edit-modal">
    <div className="loan-edit-hero"><div className="admin-modal-head"><div><div className="admin-eyebrow">LOAN CASE · EDIT</div><h2>{editing.loan_account_no||editing.application_no||'Loan Case'}</h2><div className="muted">{editing.customer_profiles?.full_name||editing.customer_name||'Applicant'} {editing.customer_profiles?.phone||editing.customer_phone?` · ${editing.customer_profiles?.phone||editing.customer_phone}`:''}</div><div className="loan-edit-id">✎ Edit existing loan record</div></div><button type="button" className="admin-btn secondary" aria-label="Close" onClick={()=>setEditing(null)}>✕</button></div></div>
    <form className="loan-edit-body" onSubmit={save}>
      <div className="loan-edit-section"><div className="loan-edit-section-title"><span className="section-icon">🚗</span> Vehicle & File Details</div><div className="form-grid">
        <div><label>Vehicle No.</label><input value={editing.vehicle_no} onChange={e=>setEditing({...editing,vehicle_no:e.target.value.toUpperCase()})} placeholder="e.g. DL10ER1697"/></div>
        <div><label>Chassis No.</label><input value={editing.chassis_no} onChange={e=>setEditing({...editing,chassis_no:e.target.value.toUpperCase()})} placeholder="Chassis number"/></div>
        <div><label>Ledger / Physical Register No.</label><input value={editing.ledger_no} onChange={e=>setEditing({...editing,ledger_no:e.target.value.toUpperCase()})} placeholder="Ledger number"/></div>
        <div><label>File No.</label><input value={editing.file_no} onChange={e=>setEditing({...editing,file_no:e.target.value})} placeholder="File number"/></div>
        <div><label>File Record No.</label><input value={editing.file_record_no} onChange={e=>setEditing({...editing,file_record_no:e.target.value})} placeholder="File record number"/></div>
        <div><label>Cheques Qty</label><input type="number" min="0" value={editing.cheques_qty} onChange={e=>setEditing({...editing,cheques_qty:e.target.value})}/></div>
      </div></div>
      <div className="loan-edit-section"><div className="loan-edit-section-title"><span className="section-icon">📌</span> Loan & Case Status</div><div className="form-grid">
        <div><label>Loan Stage</label><select value={editing.loan_status} onChange={e=>setEditing({...editing,loan_status:e.target.value})}><option value="sanctioned">Sanctioned</option><option value="disbursed">Disbursed</option></select></div>
        <div><label>Case Status</label><select value={editing.case_status} onChange={e=>setEditing({...editing,case_status:e.target.value})}><option value="active">Active</option><option value="suit_filed">Suit Filed</option><option value="vehicle_seized">Vehicle Seized</option><option value="closed">Closed</option><option value="written_off">Written Off</option></select></div>
        <div><label>Disbursement Date</label><input type="date" value={editing.disbursement_date} onChange={e=>setEditing({...editing,disbursement_date:e.target.value})}/></div>
        <div><label>Disbursed Amount</label><input type="number" min="0" value={editing.disbursed_amount} onChange={e=>setEditing({...editing,disbursed_amount:e.target.value})} placeholder="Amount"/></div>
      </div></div>
      <div className="loan-edit-section loan-edit-readonly"><div className="loan-edit-section-title"><span className="section-icon">👤</span> Applicant Summary</div><div className="detail-grid"><div><small>Application</small><strong>{editing.application_no||'—'}</strong></div><div><small>Loan Account</small><strong>{editing.loan_account_no||'—'}</strong></div><div><small>Customer</small><strong>{editing.customer_profiles?.full_name||editing.customer_name||'—'}</strong></div><div><small>Mobile</small><strong>{editing.customer_profiles?.phone||editing.customer_phone||'—'}</strong></div></div></div>
      <div className="loan-edit-footer"><button type="button" className="admin-btn secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="admin-btn" disabled={saving}>{saving?'Saving…':'✓ Save Changes'}</button></div>
    </form>
   </section></div>}
   {preview&&<div style={{position:'fixed',inset:0,zIndex:120,background:'rgba(0,0,0,.35)'}} onMouseDown={e=>{if(e.target===e.currentTarget)setPreview(null)}}>
     <aside style={{position:'absolute',right:0,top:0,height:'100%',width:'min(520px,96vw)',background:'#fff',boxShadow:'-8px 0 30px rgba(0,0,0,.18)',overflowY:'auto',padding:24}}>
       <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:15,borderBottom:'1px solid #eee',paddingBottom:16}}><div><div className="admin-eyebrow">LOAN DETAIL</div><h2 style={{margin:'5px 0 0',fontSize:24}}>{preview.loan.loan_account_no||'Loan'}</h2><div className="muted">{preview.loan.customer_profiles?.full_name||preview.loan.customer_name||'—'}</div></div><button className="admin-btn secondary" onClick={()=>setPreview(null)}>✕ Close</button></div>
       <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:20}}>{[['Customer',preview.loan.customer_profiles?.full_name||preview.loan.customer_name],['Mobile',preview.loan.customer_profiles?.phone||preview.loan.customer_phone],['Vehicle No.',preview.loan.vehicle_no],['Chassis No.',preview.loan.chassis_no],['Ledger No.',preview.loan.ledger_no],['File No.',preview.loan.file_no],['Loan Amount',money(preview.loan.loan_amount_requested)],['Case Status',String(preview.loan.case_status||'active').replaceAll('_',' ')],['Approval Valid Till',preview.loan.approval_valid_until],['Disbursement Date',preview.loan.disbursement_date],['Repo Date',preview.loan.vehicle_repossessions?.[0]?.repo_date],['Repo Time',preview.loan.vehicle_repossessions?.[0]?.repo_time],['Repo Vehicle',preview.loan.vehicle_repossessions?.[0]?.vehicle_no],['Battery',preview.loan.vehicle_repossessions?.[0]?.battery_available?`${preview.loan.vehicle_repossessions?.[0]?.battery_master?.battery_name||'Yes'} · ${preview.loan.vehicle_repossessions?.[0]?.battery_no||'—'}`:'No'],['RC',preview.loan.vehicle_repossessions?.[0]?.rc_available?'Yes':'No'],['Charger',preview.loan.vehicle_repossessions?.[0]?.charger_available?'Yes':'No'],['Parked At',preview.loan.vehicle_repossessions?.[0]?.dealer_master?.dealer_name]].map(([k,v])=><div key={k} style={{border:'1px solid #eee',borderRadius:10,padding:12}}><div style={{fontSize:11,color:'#777',textTransform:'uppercase'}}>{k}</div><strong style={{display:'block',marginTop:5}}>{v||'—'}</strong></div>)}</div>
       <div style={{marginTop:20,padding:14,borderRadius:10,background:'#fff6f1',border:'1px solid #f0d7c8'}}><strong>Receipts</strong><div style={{marginTop:5}}>{previewLoading?'Loading receipts…':`${preview.receipts.length} receipt${preview.receipts.length===1?'':'s'} · ${money(preview.receipts.reduce((n,r)=>n+Number(r.amount||0),0))} received`}</div></div>
       <div style={{display:'flex',gap:10,marginTop:22}}><button className="admin-btn" disabled={previewLoading} onClick={()=>printLoanDetail(preview.loan,preview.receipts)}>🖨 Print Loan Detail / PDF</button><button className="admin-btn secondary" onClick={()=>setEditing({...preview.loan,loan_application_id:preview.loan.id,case_status:preview.loan.case_status||'active',loan_status:preview.loan.application_status||'sanctioned',vehicle_no:preview.loan.vehicle_no||'',chassis_no:preview.loan.chassis_no||'',ledger_no:preview.loan.ledger_no||'',file_no:preview.loan.file_no||'',file_record_no:preview.loan.file_record_no||'',cheques_qty:preview.loan.cheques_qty||0,disbursement_date:preview.loan.disbursement_date||'',disbursed_amount:preview.loan.disbursed_amount||''})}>Edit Case</button></div>
     </aside>
   </div>}
 </div>
}
