import { useState } from 'react';
import { createManualLoan } from './api';

const initial = {dealer_name:'',dealer_code:'',dealer_phone:'',customer_name:'',customer_phone:'',customer_dob:'',customer_pan:'',customer_address:'',customer_city:'',customer_state:'',customer_pincode:'',vehicle_model:'',vehicle_price:'',down_payment:'',loan_amount:'',tenure_months:'36',loan_type:'',hypothecation:'',loan_account_no:'',vehicle_no:'',chassis_no:'',engine_no:'',disbursement_date:new Date().toISOString().slice(0,10),disbursed_amount:'',remarks:''};

export default function ManualCreateLoan(){
 const [form,setForm]=useState(initial),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState('');
 const set=(k,v)=>setForm(f=>({...f,[k]:v})),calc=()=>Math.max(0,Number(form.vehicle_price||0)-Number(form.down_payment||0));
 async function submit(e){e.preventDefault();setSaving(true);setMsg('');setError('');try{const d=await createManualLoan({...form,loan_amount:form.loan_amount||calc(),disbursed_amount:form.disbursed_amount||form.loan_amount||calc()});setMsg(d.message||'Loan created successfully.');setForm(initial)}catch(err){setError(err.message||'Could not create loan.')}finally{setSaving(false)}}
 return <div className="admin-page"><div className="admin-page-head"><div><div className="admin-eyebrow">DIRECT ENTRY</div><h1>Manual Create Loan</h1><p>Admin se direct loan create karein. Dealer details manually enter hongi.</p></div></div>
 {msg&&<div className="admin-alert success">✓ {msg}</div>}{error&&<div className="admin-alert error">⚠ {error}</div>}
 <form className="admin-card staff-form" onSubmit={submit}>
 <h2>Dealer Details</h2><div className="form-grid"><div><label>Dealer Name *</label><input required value={form.dealer_name} onChange={e=>set('dealer_name',e.target.value)} /></div><div><label>Dealer Code</label><input value={form.dealer_code} onChange={e=>set('dealer_code',e.target.value.toUpperCase())}/></div><div><label>Dealer Mobile</label><input inputMode="numeric" maxLength="10" value={form.dealer_phone} onChange={e=>set('dealer_phone',e.target.value.replace(/\D/g,'').slice(0,10))}/></div></div>
 <h2>Customer Details</h2><div className="form-grid"><div><label>Customer Name *</label><input required value={form.customer_name} onChange={e=>set('customer_name',e.target.value)}/></div><div><label>Mobile *</label><input required inputMode="numeric" maxLength="10" value={form.customer_phone} onChange={e=>set('customer_phone',e.target.value.replace(/\D/g,'').slice(0,10))}/></div><div><label>Date of Birth</label><input type="date" value={form.customer_dob} onChange={e=>set('customer_dob',e.target.value)}/></div><div><label>PAN</label><input maxLength="10" value={form.customer_pan} onChange={e=>set('customer_pan',e.target.value.toUpperCase())}/></div><div className="form-field-full"><label>Address</label><input value={form.customer_address} onChange={e=>set('customer_address',e.target.value)}/></div><div><label>City</label><input value={form.customer_city} onChange={e=>set('customer_city',e.target.value)}/></div><div><label>State</label><input value={form.customer_state} onChange={e=>set('customer_state',e.target.value)}/></div><div><label>Pincode</label><input maxLength="6" inputMode="numeric" value={form.customer_pincode} onChange={e=>set('customer_pincode',e.target.value.replace(/\D/g,'').slice(0,6))}/></div></div>
 <h2>Vehicle & Loan</h2><div className="form-grid"><div><label>Vehicle Model *</label><input required value={form.vehicle_model} onChange={e=>set('vehicle_model',e.target.value)}/></div><div><label>Vehicle Price *</label><input required type="number" min="0" value={form.vehicle_price} onChange={e=>set('vehicle_price',e.target.value)}/></div><div><label>Down Payment *</label><input required type="number" min="0" value={form.down_payment} onChange={e=>set('down_payment',e.target.value)}/></div><div><label>Loan Amount</label><input type="number" min="0" value={form.loan_amount} onChange={e=>set('loan_amount',e.target.value)} placeholder={String(calc())}/></div><div><label>Tenure *</label><select required value={form.tenure_months} onChange={e=>set('tenure_months',e.target.value)}>{[12,18,24,30,36,48,60].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Loan Type</label><input value={form.loan_type} onChange={e=>set('loan_type',e.target.value)}/></div><div><label>Hypothecation / HP</label><input value={form.hypothecation} onChange={e=>set('hypothecation',e.target.value)}/></div><div><label>Loan Account No.</label><input value={form.loan_account_no} onChange={e=>set('loan_account_no',e.target.value.toUpperCase())} placeholder="Blank = auto generate"/></div></div>
 <h2>Disbursement / Vehicle</h2><div className="form-grid"><div><label>Disbursement Date</label><input type="date" value={form.disbursement_date} onChange={e=>set('disbursement_date',e.target.value)}/></div><div><label>Disbursed Amount</label><input type="number" min="0" value={form.disbursed_amount} onChange={e=>set('disbursed_amount',e.target.value)}/></div><div><label>Vehicle No.</label><input value={form.vehicle_no} onChange={e=>set('vehicle_no',e.target.value.toUpperCase())}/></div><div><label>Chassis No.</label><input value={form.chassis_no} onChange={e=>set('chassis_no',e.target.value.toUpperCase())}/></div><div><label>Engine No.</label><input value={form.engine_no} onChange={e=>set('engine_no',e.target.value.toUpperCase())}/></div><div className="form-field-full"><label>Remarks</label><textarea rows="3" value={form.remarks} onChange={e=>set('remarks',e.target.value)}/></div></div>
 <button className="admin-btn" disabled={saving}>{saving?'Creating…':'✓ Create Loan'}</button></form></div>
}