import { useEffect, useState } from 'react';
import { listTVR, decideTVR } from './api';
const label=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
export default function TVRReview({onMessage,onError}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[remarks,setRemarks]=useState({});
 async function load(){setLoading(true);try{const d=await listTVR();setRows(d.tvrs||[])}catch(e){onError?.(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 async function decide(t,decision){setBusy(t.id);onError?.('');try{const d=await decideTVR({tvr_id:t.id,decision,remarks:remarks[t.id]||''});onMessage?.(d.message||`TVR ${decision}.`);await load()}catch(e){onError?.(e.message)}finally{setBusy(null)}}
 return <section className="admin-card staff-list-card tvr-review"><div className="admin-card-title"><div><div className="admin-eyebrow">DISBURSEMENT GATE</div><h2>TVR Verification</h2><span>Verify submitted TVR before loan creation / disbursement</span></div><button className="admin-btn secondary" onClick={load} disabled={loading}>↻ Refresh</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Application</th><th>Customer</th><th>Verification</th><th>Checks</th><th>Recommendation</th><th>Decision</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="empty-cell">Loading TVR…</td></tr>:rows.length===0?<tr><td colSpan="6" className="empty-cell">No submitted TVR cases.</td></tr>:rows.map(t=>{const a=t.loan_applications||{};const c=a.customer_profiles||{};const checks=[t.customer_contacted,t.applicant_confirmed,t.address_confirmed,t.employment_confirmed,t.reference_confirmed,t.documents_checked,t.vehicle_details_confirmed];return <tr key={t.id}><td><strong>{a.application_no||'—'}</strong><div className="muted">₹{Number(a.loan_amount_requested||0).toLocaleString('en-IN')}</div></td><td className="contact-text"><div>{c.full_name||'—'}</div><div className="muted">{c.phone||'—'}</div><div className="muted">{c.address||'—'}</div></td><td>{t.verification_date||'—'}<div className="muted">{String(t.verification_time||'').slice(0,5)}</div><div className="muted">{t.remarks||'—'}</div></td><td><span className="tvr-check-count">{checks.filter(Boolean).length}/7 checks</span>{t.reference_name&&<div className="muted">Ref: {t.reference_name}</div>}</td><td><span className={`role-pill ${t.recommendation==='positive'?'field_executive':t.recommendation==='negative'?'staff':''}`}>{label(t.recommendation)}</span><div className="muted">{label(t.status)}</div></td><td className="actions-cell">{t.status==='submitted'?<><input placeholder="Decision remarks" value={remarks[t.id]||''} onChange={e=>setRemarks(r=>({...r,[t.id]:e.target.value}))}/><div style={{display:'flex',gap:6,marginTop:6}}><button className="admin-btn small" disabled={busy===t.id} onClick={()=>decide(t,'verified')}>✓ Verify</button><button className="admin-btn small secondary" disabled={busy===t.id} onClick={()=>decide(t,'hold')}>Hold</button><button className="admin-btn small danger" disabled={busy===t.id} onClick={()=>decide(t,'failed')}>Reject</button></div></>:<span className="muted">{label(t.status)}</span>}</td></tr>})}</tbody></table></div></section>
}
