import ProfileMenu from '../../components/ProfileMenu';
import CollectionActivity from '../../components/CollectionActivity';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { apiGet, clearAppUserToken } from '../../utils/appUserAuth';
import { getCurrentUser, clearCurrentUser } from '../../utils/session';
function money(v){return `₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`}
function label(v){return String(v||'—').replaceAll('_',' ')}
export default function CustomerPaymentDashboard(){
 const navigate=useNavigate(), user=getCurrentUser()||{}; const [loans,setLoans]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 function logout(){clearCurrentUser();clearAppUserToken();navigate('/login')}
 useEffect(()=>{apiGet('/api/customer','my-loans').then(d=>setLoans(d.loans||[])).catch(e=>setError(e.message||'Could not load loans')).finally(()=>setLoading(false))},[]);
 return <div className="customer-shell"><header className="customer-header"><div><div className="customer-brand">Capital Hind Finance</div><div className="customer-sub">Customer Loan Portal</div></div><div><ProfileMenu compact /><span>{user.full_name||'Customer'}</span><button onClick={logout}>↪ Logout</button></div></header><main className="customer-main"><div className="customer-page-head"><div><div className="customer-eyebrow">MY LOANS</div><h1>Hello, {user.full_name||'Customer'}</h1><p>Your loan records are matched using your registered mobile number.</p></div><div className="customer-count">{loans.length} loan{loans.length===1?'':'s'}</div></div>{error&&<div className="customer-error">⚠ {error}</div>}<section className="customer-kpis"><div><span>Total Loans</span><strong>{loading?'—':loans.length}</strong></div><div><span>Active Cases</span><strong>{loading?'—':loans.filter(l=>l.case_status==='active').length}</strong></div><div><span>Disbursed</span><strong>{loading?'—':loans.filter(l=>l.application_status==='disbursed').length}</strong></div><div><span>Outstanding / Loan Amount</span><strong>{loading?'—':money(loans.reduce((n,l)=>n+Number(l.loan_amount_requested||0),0))}</strong></div></section><section className="customer-card"><div className="customer-card-head"><div><h2>My loan accounts</h2><p>Application, loan account, vehicle and current case status.</p></div></div><div className="customer-table-wrap"><table className="customer-table"><thead><tr><th>Loan / Application</th><th>Vehicle</th><th>Amount</th><th>Status</th><th>Case</th><th>Approval Validity</th><th>Receipts</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="customer-empty">Loading…</td></tr>:loans.map(l=><tr key={l.id}><td><strong>{l.loan_account_no||'Not created'}</strong><small>{l.application_no}</small></td><td>{l.vehicle_model_master?.model_name||'—'}<small>{l.vehicle_no||l.chassis_no||''}</small></td><td>{money(l.loan_amount_requested)}</td><td><span className="customer-status">{label(l.application_status)}</span></td><td>{label(l.case_status)}</td><td>{l.approval_valid_until||'—'}</td><td>{(l.loan_receipts||[]).length?`${l.loan_receipts.length} receipt(s)`:'No receipt'}</td></tr>)}{!loading&&!loans.length&&<tr><td colSpan="7" className="customer-empty">No loan found for this registered mobile number.</td></tr>}</tbody></table></div></section><CollectionActivity compact />
    </main></div>
}
