import ProfileMenu from '../../components/ProfileMenu';
import RoleNavigation from '../../components/RoleNavigation';
import CollectionActivity from '../../components/CollectionActivity';
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { clearCurrentUser, getCurrentUser } from '../../utils/session';
import { clearAppUserToken, apiGet, apiPost } from '../../utils/appUserAuth';

const OUTCOMES=[['connected','Connected'],['not_connected','Not connected'],['callback','Callback required'],['interested','Interested'],['not_interested','Not interested'],['wrong_number','Wrong number'],['promise_to_pay','Promise to pay'],['paid','Paid'],['do_not_call','Do not call']];
const FILTERS=[['all','All'],['today','Due today'],['callback','Callbacks'],['overdue_callback','Overdue callback'],['ptp','PTP'],['uncalled','Not contacted']];
function money(v){return `₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`}
function dateOnly(v){return v?new Date(v).toLocaleDateString('en-IN'): '—'}
function dateTime(v){return v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'—'}
function statusLabel(v){return String(v||'unknown').replaceAll('_',' ')}

export default function TeleCallerDashboard(){
 const navigate=useNavigate(), user=getCurrentUser()||{};
 const [data,setData]=useState({registers:[],applications:[],stats:{},followups:[],overdue_callbacks:[],upcoming_callbacks:[],ptp_broken:[]});
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[active,setActive]=useState(null),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');
 const [form,setForm]=useState({outcome:'connected',notes:'',callback_at:'',ptp_date:'',ptp_amount:''}),[saving,setSaving]=useState(false);
 function logout(){clearAppUserToken();clearCurrentUser();navigate('/login',{replace:true})}
 async function load(){setLoading(true);setError('');try{setData(await apiGet('/api/tele-caller','dashboard'))}catch(e){setError(e.message||'Could not load dashboard')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const today=new Date(); const todayIso=today.toISOString().slice(0,10);
 const queue=useMemo(()=>{let rows=data.applications||[]; const q=search.trim().toLowerCase(); if(q) rows=rows.filter(a=>[a.application_no,a.loan_account_no,a.customer_name,a.customer_phone,a.physical_register_serial_no].some(v=>String(v||'').toLowerCase().includes(q)));
  return rows.filter(a=>{if(filter==='all')return true;if(filter==='today')return a.last_call?.callback_at?.slice(0,10)===todayIso;if(filter==='callback')return !!a.last_call?.callback_at;if(filter==='overdue_callback')return data.overdue_callbacks?.some(x=>x.id===a.id);if(filter==='ptp')return a.ptp?.status==='open';if(filter==='uncalled')return !a.last_call;return true});},[data.applications,data.overdue_callbacks,filter,search,todayIso]);
 function openCall(a){setActive(a);setForm({outcome:'connected',notes:'',callback_at:'',ptp_date:'',ptp_amount:''})}
 async function saveCall(e){e.preventDefault();if(!active)return;setSaving(true);setError('');try{await apiPost('/api/tele-caller','log-call',{loan_application_id:active.id,...form,callback_at:form.callback_at||null,ptp_date:form.outcome==='promise_to_pay'?form.ptp_date:null,ptp_amount:form.outcome==='promise_to_pay'?form.ptp_amount:null});setActive(null);await load()}catch(e){setError(e.message||'Could not save call')}finally{setSaving(false)}}
 return <div className="tele-shell"><RoleNavigation role="tele_caller"/>
  <header className="tele-header"><div><div className="tele-brand">Capital Hind Finance</div><div className="tele-sub">Tele Caller • Collection CRM</div></div><div className="tele-header-right"><span>{user.full_name||'Tele Caller'}</span><ProfileMenu compact/><button onClick={logout}>↪ Logout</button></div></header>
  <main className="tele-main">
   <div className="tele-page-head"><div><div className="tele-eyebrow">CALLING & COLLECTION DESK</div><h1>Good to see you, {user.full_name||'Tele Caller'}</h1><p>Assigned loan cases, follow-ups, PTP aur customer calling ek jagah manage karein.</p></div><button className="tele-refresh" onClick={load} disabled={loading}>↻ Refresh</button></div>
   {error&&<div className="tele-error">⚠ {error}</div>}
   <section className="tele-kpis tele-kpis-6">
    <div><span>Assigned Registers</span><strong>{loading?'—':data.stats.registers||0}</strong></div><div><span>Calling Queue</span><strong>{loading?'—':data.stats.queue||0}</strong></div><div><span>Calls Today</span><strong>{loading?'—':data.stats.calls_today||0}</strong></div><div><span>Connected Today</span><strong>{loading?'—':data.stats.connected_today||0}</strong></div><div><span>Callback Due</span><strong className="tele-danger-num">{loading?'—':data.stats.callbacks_due||0}</strong></div><div><span>PTP Today</span><strong>{loading?'—':data.stats.ptp_today||0}</strong></div>
   </section>
   <section className="tele-kpis tele-kpis-4 tele-kpis-secondary"><div><span>PTP Amount Open</span><strong>{loading?'—':money(data.stats.ptp_amount)}</strong></div><div><span>Broken PTP</span><strong className="tele-danger-num">{loading?'—':data.stats.ptp_broken||0}</strong></div><div><span>Not Contacted</span><strong>{loading?'—':data.stats.new_cases||0}</strong></div><div><span>Contact Rate</span><strong>{loading?'—':`${data.stats.contact_rate||0}%`}</strong></div></section>
   <section className="tele-grid tele-work-grid">
    <div className="tele-card"><div className="tele-card-head"><div><h2>Today's worklist</h2><p>Sabse pehle due aur risk cases handle karein.</p></div></div><div className="tele-work-list"><button onClick={()=>setFilter('today')}><b>🟠 Today's follow-ups</b><strong>{data.stats.callbacks||0}</strong></button><button onClick={()=>setFilter('overdue_callback')}><b>🔴 Overdue callbacks</b><strong>{data.stats.callbacks_due||0}</strong></button><button onClick={()=>setFilter('ptp')}><b>🟡 Open PTP</b><strong>{data.ptp_broken?.length||0} broken</strong></button><button onClick={()=>setFilter('uncalled')}><b>🔵 New / not contacted</b><strong>{data.stats.new_cases||0}</strong></button></div></div>
    <div className="tele-card"><div className="tele-card-head"><div><h2>My registers</h2><p>Team Leader se assigned physical ledgers.</p></div></div><div className="tele-registers">{data.registers.length?data.registers.map(r=><div className="tele-register" key={r.id}><strong>{r.register_serial_no}</strong><span>{dateOnly(r.assigned_at)}</span></div>):<div className="tele-empty">No register assigned yet.</div>}</div></div>
   </section>
   <section className="tele-card tele-queue"><div className="tele-card-head tele-queue-head"><div><h2>Calling Queue</h2><p>Sirf aapke active assigned registers ke loan cases.</p></div><span>{queue.length} loans</span></div>
    <div className="tele-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer, mobile, application or loan…"/><div className="tele-filters">{FILTERS.map(([v,l])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{l}</button>)}</div></div>
    <div className="tele-table-wrap"><table className="tele-table"><thead><tr><th>Register</th><th>Customer</th><th>Loan / EMI</th><th>Status</th><th>Last Call</th><th>PTP</th><th>Action</th></tr></thead><tbody>
      {queue.map(a=><tr key={a.id}><td><strong>{a.physical_register_serial_no||'—'}</strong><small>{a.application_no||'—'}</small></td><td><strong>{a.customer_name||'—'}</strong><small>{a.customer_phone||'—'}{a.vehicle_model?` • ${a.vehicle_model}`:''}</small></td><td><strong>{money(a.loan_amount_requested)}</strong><small>{a.loan_account_no||'—'} • {a.tenure_months||'—'} months</small></td><td><span className="tele-status">{statusLabel(a.application_status)}</span></td><td>{a.last_call?<><b>{statusLabel(a.last_call.outcome)}</b><small>{dateTime(a.last_call.called_at)}{a.last_call.callback_at?` • CB ${dateTime(a.last_call.callback_at)}`:''}</small></>:<span className="tele-muted">Not contacted</span>}</td><td>{a.ptp?<><b>{money(a.ptp.promised_amount)}</b><small>{dateOnly(a.ptp.promised_date)} • {a.ptp.status}</small></>:<span className="tele-muted">—</span>}</td><td><button className="tele-call-btn" onClick={()=>openCall(a)}>☎ Call / update</button></td></tr>)}
      {!loading&&!queue.length&&<tr><td colSpan="7" className="tele-empty">No cases match this filter.</td></tr>}
    </tbody></table></div></section>
    <section className="tele-grid tele-bottom-grid"><div className="tele-card"><div className="tele-card-head"><div><h2>Upcoming follow-ups</h2><p>Next 7 days</p></div></div><div className="tele-follow-list">{(data.upcoming_callbacks||[]).slice(0,8).map(a=><button key={a.id} onClick={()=>openCall(a)}><span><b>{a.customer_name||a.application_no}</b><small>{dateTime(a.last_call?.callback_at)} • {a.customer_phone||'—'}</small></span><strong>Call</strong></button>)}{!data.upcoming_callbacks?.length&&<div className="tele-empty">No upcoming callbacks.</div>}</div></div><div className="tele-card"><div className="tele-card-head"><div><h2>Broken PTP</h2><p>Immediate follow-up required</p></div></div><div className="tele-follow-list">{(data.ptp_broken||[]).slice(0,8).map(a=><button key={a.id} onClick={()=>openCall(a)}><span><b>{a.customer_name||a.application_no}</b><small>{money(a.ptp?.promised_amount)} promised • {dateOnly(a.ptp?.promised_date)}</small></span><strong className="tele-danger-text">Call</strong></button>)}{!data.ptp_broken?.length&&<div className="tele-empty">No broken PTP.</div>}</div></div></section>
    <CollectionActivity compact/>
  </main>
  {active&&<div className="tele-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setActive(null)}><form className="tele-modal tele-modal-large" onSubmit={saveCall}><div className="tele-modal-head"><div><h2>Customer 360 • Call Update</h2><p>{active.customer_name} • {active.customer_phone} • {active.application_no} • {active.loan_account_no}</p></div><button type="button" onClick={()=>setActive(null)}>×</button></div><div className="tele-customer-grid"><div><span>Loan Amount</span><b>{money(active.loan_amount_requested)}</b></div><div><span>Tenure</span><b>{active.tenure_months||'—'} months</b></div><div><span>Vehicle</span><b>{active.vehicle_model||'—'}</b></div><div><span>Register</span><b>{active.physical_register_serial_no||'—'}</b></div></div><div className="tele-history"><h3>Recent call history</h3>{active.call_history?.length?active.call_history.map(l=><div key={l.id}><b>{statusLabel(l.outcome)}</b><span>{dateTime(l.called_at)}</span><small>{l.notes||'No note'}</small></div>):<p>No previous calls.</p>}</div><label>Call outcome<select value={form.outcome} onChange={e=>setForm({...form,outcome:e.target.value})}>{OUTCOMES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Callback date & time <span>(optional)</span><input type="datetime-local" value={form.callback_at} onChange={e=>setForm({...form,callback_at:e.target.value})}/></label>{form.outcome==='promise_to_pay'&&<div className="tele-ptp-grid"><label>PTP date<input type="date" value={form.ptp_date} onChange={e=>setForm({...form,ptp_date:e.target.value})} required/></label><label>PTP amount<input type="number" min="1" step="0.01" value={form.ptp_amount} onChange={e=>setForm({...form,ptp_amount:e.target.value})} placeholder="₹" required/></label></div>}<label>Remarks / call notes<textarea rows="4" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Customer se baat, reason, commitment aur next action…"/></label><div className="tele-modal-actions"><button type="button" className="secondary-button" onClick={()=>setActive(null)}>Cancel</button><button className="tele-primary" disabled={saving}>{saving?'Saving…':'Save call details'}</button></div></form></div>}
 </div>
}
