-- OEM master + standalone receipt workflow.
create table if not exists public.vehicle_oem_master (
  id bigint generated by default as identity primary key,
  oem_name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Add OEM relation to the existing vehicle model master when that table exists.
do $$
begin
  if to_regclass('public.vehicle_model_master') is not null then
    alter table public.vehicle_model_master
      add column if not exists oem_id bigint;
    if not exists (
      select 1 from pg_constraint
      where conname = 'vehicle_model_master_oem_id_fkey'
    ) then
      alter table public.vehicle_model_master
        add constraint vehicle_model_master_oem_id_fkey
        foreign key (oem_id) references public.vehicle_oem_master(id) on delete set null;
    end if;
  end if;
end $$;

create index if not exists vehicle_oem_master_active_idx
  on public.vehicle_oem_master(is_active, oem_name);

-- Receipt table is also created here so a fresh install gets the standalone receipt tab.
create table if not exists public.loan_receipts (
  id uuid primary key default gen_random_uuid(),
  loan_application_id bigint not null references public.loan_applications(id) on delete cascade,
  receipt_no text not null unique,
  receipt_date date not null default current_date,
  amount numeric not null check (amount > 0),
  payment_mode text not null default 'cash' check (payment_mode in ('cash','upi','bank','cheque','other')),
  reference_no text,
  remarks text,
  entered_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists loan_receipts_loan_idx on public.loan_receipts(loan_application_id, receipt_date desc);

alter table public.loan_receipts enable row level security;
