-- Co-borrower details: one optional co-borrower per loan application.
create table if not exists public.co_borrower_details (
  id bigint generated by default as identity primary key,
  loan_application_id bigint not null references public.loan_applications(id) on delete cascade,
  full_name text not null,
  relation_with_customer text,
  phone text,
  email text,
  dob date,
  gender text,
  address text,
  city text,
  state text,
  pincode text,
  pan text,
  aadhaar_masked text,
  occupation text,
  monthly_income numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (loan_application_id)
);
create index if not exists co_borrower_details_loan_idx on public.co_borrower_details(loan_application_id);
alter table public.co_borrower_details enable row level security;
