-- Dealer login compatibility / bootstrap.
-- The application expects public.dealer_master and public.dealer_users.
-- This migration is safe on installations where these tables already exist.

create table if not exists public.dealer_master (
  id bigint generated by default as identity primary key,
  dealer_code text unique,
  dealer_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.dealer_users (
  id uuid primary key default gen_random_uuid(),
  dealer_id bigint not null references public.dealer_master(id) on delete cascade,
  full_name text not null,
  phone text not null,
  password_hash text not null,
  role text not null default 'dealer',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Bring older dealer_users tables up to the fields required by the current API.
alter table public.dealer_users
  add column if not exists dealer_id bigint,
  add column if not exists full_name text,
  add column if not exists phone text,
  add column if not exists password_hash text,
  add column if not exists role text default 'dealer',
  add column if not exists is_active boolean default true,
  add column if not exists created_at timestamptz default now();

create unique index if not exists dealer_users_phone_uq
  on public.dealer_users(phone);
create index if not exists dealer_users_dealer_idx
  on public.dealer_users(dealer_id);
create index if not exists dealer_users_active_idx
  on public.dealer_users(is_active);

-- Server-side APIs use the service-role key.
alter table public.dealer_master enable row level security;
alter table public.dealer_users enable row level security;
