import { useEffect, useState } from 'react';
import { listTVR, submitTVR } from './api';

const empty = { verification_date:new Date().toISOString().slice(0,10), verification_time:'', customer_contacted:false, applicant_confirmed:false, address_confirmed:false, employment_confirmed:false, reference_confirmed:false, documents_checked:false, vehicle_details_confirmed:false, alternate_mobile_no:'', reference_name:'', reference_mobile:'', remarks:'', recommendation:'positive' };
const label = s => String(s||'pending').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());

export default function TVRModule({ onMessage, onError }) {
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[active,setActive]=useState(null),[form,setForm]=useState(empty),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{const d=await listTVR();setRows(d.applications||[])}catch(e){onError?.(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function start(r){setActive(r);setForm({...empty,verification_time:new Date().toTimeString().slice(0,5),recommendation:'positive'});onError?.('')}
 function set(k,v){setForm(f=>({...f,[k]:v}))}
 async function submit(e){e.preventDefault();if(!active)return;setSaving(true);onError?.('');try{const d=await submitTVR({loan_application_id:active.id,...form});onMessage?.(d.message||'TVR submitted successfully.');setActive(null);await load()}catch(e){onError?.(e.message)}finally{setSaving(false)}}
 return <section className="admin-card staff-list-card tvr-card" id="fe-tvr">
  <div className="admin-card-title"><div><div className="admin-eyebrow">POST-APPROVAL VERIFICATION</div><h2>TVR — Tele Verification Report</h2><span>Approved loans only · complete TVR before loan creation / disbursement</span></div><button className="admin-btn secondary" onClick={load} disabled={loading}>↻ Refresh</button></div>
  <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Application</th><th>Customer</th><th>Vehicle / Dealer</th><th>TVR Status</th><th>Action</th></tr></thead><tbody>
   {loading?<tr><td colSpan="5" className="empty-cell">Loading TVR cases…</td></tr>:rows.length===0?<tr><td colSpan="5" className="empty-cell">No approved loan is pending TVR.</td></tr>:rows.map(r=><tr key={r.id}><td><strong>{r.application_no}</strong><div className="muted">Approved {r.approved_at?new Date(r.approved_at).toLocaleDateString('en-IN'):'—'}</div></td><td className="contact-text"><div>{r.customer_name||'—'}</div><div className="muted">{r.customer_phone||'—'}</div><div className="muted">{r.customer_address||'—'}</div></td><td>{r.vehicle_model||'—'}<div className="muted">{r.dealer_name||'—'}</div></td><td><span className={`role-pill ${r.tvr_status==='verified'?'field_executive':r.tvr_status==='failed'?'staff':''}`}>{label(r.tvr_status)}</span></td><td className="actions-cell">{r.tvr_status!=='verified'?<button className="admin-btn small" onClick={()=>start(r)}>{r.tvr_status==='submitted'?'Edit / Resubmit TVR':'Start TVR'}</button>:<span className="muted">✓ Verified</span>}</td></tr>)}
  </tbody></table></div>
  {active&&<div className="fe-modal-backdrop"><form className="fe-collection-modal tvr-form" onSubmit={submit}><div className="admin-card-title"><div><div className="admin-eyebrow">TVR CASE</div><h2>Tele Verification — {active.application_no}</h2><span>{active.customer_name||'Customer'} · {active.customer_phone||'No mobile'}</span></div><button type="button" className="admin-btn secondary" onClick={()=>setActive(null)}>✕ Close</button></div>
   <div className="tvr-summary"><div><b>Address</b><span>{active.customer_address||'—'}{active.customer_city?`, ${active.customer_city}`:''}</span></div><div><b>Vehicle</b><span>{active.vehicle_model||'—'}</span></div><div><b>Dealer</b><span>{active.dealer_name||'—'}</span></div></div>
   <div className="form-grid"><div><label>Verification date</label><input type="date" value={form.verification_date} onChange={e=>set('verification_date',e.target.value)} required/></div><div><label>Verification time</label><input type="time" value={form.verification_time} onChange={e=>set('verification_time',e.target.value)} required/></div><div><label>Alternate mobile</label><input value={form.alternate_mobile_no} onChange={e=>set('alternate_mobile_no',e.target.value)} placeholder="If different"/></div><div><label>Recommendation</label><select value={form.recommendation} onChange={e=>set('recommendation',e.target.value)}><option value="positive">Positive</option><option value="negative">Negative</option><option value="hold">Hold</option></select></div><div className="full"><label>Reference name</label><input value={form.reference_name} onChange={e=>set('reference_name',e.target.value)} placeholder="Reference person"/></div><div><label>Reference mobile</label><input value={form.reference_mobile} onChange={e=>set('reference_mobile',e.target.value)} /></div>
    <div className="full tvr-checks">{[['customer_contacted','Customer contacted'],['applicant_confirmed','Applicant identity/details confirmed'],['address_confirmed','Address confirmed'],['employment_confirmed','Employment / business confirmed'],['reference_confirmed','Reference confirmed'],['documents_checked','Documents checked'],['vehicle_details_confirmed','Vehicle details confirmed']].map(([k,l])=><label key={k}><input type="checkbox" checked={form[k]} onChange={e=>set(k,e.target.checked)}/><span>{l}</span></label>)}</div><div className="full"><label>TVR remarks</label><textarea rows="4" value={form.remarks} onChange={e=>set('remarks',e.target.value)} placeholder="Customer response, address/occupation verification, reference feedback, risk observations…" required/></div></div>
   <div className="fe-collection-actions"><button className="admin-btn" disabled={saving}>{saving?'Submitting…':'✓ Submit TVR'}</button><button type="button" className="admin-btn secondary" onClick={()=>setActive(null)}>Cancel</button></div>
  </form></div>}
 </section>
}
