import { useEffect, useState } from 'react';
import { createPaymentVoucher, listLoanApplicationsAdmin, listPaymentVouchers, listUsers } from './api';
function money(v){return `₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`}
function today(){return new Date().toISOString().slice(0,10)}
export default function PaymentVouchers(){
 const [vouchers,setVouchers]=useState([]),[users,setUsers]=useState([]),[loans,setLoans]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [form,setForm]=useState({voucher_no:'',loan_application_id:'',recipient_user_id:'',recipient_name:'',voucher_type:'incentive',amount:'',voucher_date:today(),narration:''});
 async function load(){setLoading(true);setError('');try{const [v,u,l]=await Promise.all([listPaymentVouchers(),listUsers(),listLoanApplicationsAdmin()]);setVouchers(v.vouchers||[]);setUsers((u.users||[]).filter(x=>x.is_active));setLoans(l.applications||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();setSaving(true);setError('');setMessage('');try{const selected=users.find(x=>x.id===form.recipient_user_id);await createPaymentVoucher({...form,recipient_role:selected?.role||'other'});setMessage('Payment voucher saved.');setForm({...form,voucher_no:'',amount:'',narration:''});await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="admin-page"><div className="admin-page-head"><div><div className="admin-eyebrow">PAYMENTS & INCENTIVES</div><h1>Payment Vouchers</h1><p>Loan case ke against Tele Caller, Field Executive aur other staff incentives / payments record karein.</p></div><div className="admin-count">{vouchers.length} vouchers</div></div>{error&&<div className="admin-alert error">⚠ {error}</div>}{message&&<div className="admin-alert success">✓ {message}</div>}
 <section className="admin-card"><div className="admin-card-title"><div><h2>New Payment Voucher</h2><span>Manual voucher entry</span></div></div><form className="staff-form" onSubmit={save}><div className="form-grid">
 <div><label>Voucher No.</label><input required value={form.voucher_no} onChange={e=>setForm({...form,voucher_no:e.target.value})} placeholder="PV-00001"/></div>
 <div><label>Voucher Date</label><input type="date" required value={form.voucher_date} onChange={e=>setForm({...form,voucher_date:e.target.value})}/></div>
 <div><label>Loan / Application</label><select value={form.loan_application_id} onChange={e=>setForm({...form,loan_application_id:e.target.value})}><option value="">General / no loan</option>{loans.map(l=><option key={l.id} value={l.id}>{l.loan_account_no||l.application_no} · {l.customer_name||'Customer'}</option>)}</select></div>
 <div><label>Pay To</label><select value={form.recipient_user_id} onChange={e=>setForm({...form,recipient_user_id:e.target.value,recipient_name:''})}><option value="">Other person / manual name</option>{users.map(u=><option key={u.id} value={u.id}>{u.full_name} · {u.role}</option>)}</select></div>
 {!form.recipient_user_id&&<div><label>Other Recipient Name</label><input required value={form.recipient_name} onChange={e=>setForm({...form,recipient_name:e.target.value})} placeholder="Name"/></div>}
 <div><label>Voucher Type</label><select value={form.voucher_type} onChange={e=>setForm({...form,voucher_type:e.target.value})}><option value="incentive">Incentive</option><option value="telecalling">Tele Calling</option><option value="field_visit">Field Visit</option><option value="collection">Collection</option><option value="expense">Expense</option><option value="other">Other</option></select></div>
 <div><label>Amount</label><input type="number" min="1" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div>
 <div className="form-field-full"><label>Narration / Remarks</label><textarea rows="3" value={form.narration} onChange={e=>setForm({...form,narration:e.target.value})} placeholder="Incentive / payment details"/></div>
 </div><button className="admin-btn" disabled={saving}>{saving?'Saving…':'✓ Save Payment Voucher'}</button></form></section>
 <section className="admin-card staff-list-card"><div className="admin-card-title"><div><h2>Voucher Register</h2><span>Latest payment and incentive entries</span></div><button className="admin-btn secondary" onClick={load}>↻ Refresh</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Voucher</th><th>Date</th><th>Loan</th><th>Recipient</th><th>Type</th><th>Amount</th><th>Narration</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="empty-cell">Loading…</td></tr>:vouchers.map(v=><tr key={v.id}><td><strong>{v.voucher_no}</strong></td><td>{v.voucher_date}</td><td>{v.loan_applications?.loan_account_no||v.loan_applications?.application_no||'General'}</td><td>{v.recipient_name||'—'}<div className="muted">{v.recipient_role||''}</div></td><td>{v.voucher_type}</td><td>{money(v.amount)}</td><td>{v.narration||'—'}</td></tr>)}{!loading&&!vouchers.length&&<tr><td colSpan="7" className="empty-cell">No vouchers yet.</td></tr>}</tbody></table></div></section>
 </div>
}
